### PR TITLE
Basic testing for humanize

### PR DESCRIPTION
**Pull request by sirinoks**
Besides testing also changed return formatting for SecondsToString in pkg/humanize/time.go . 
Simple things.

### CODE REVIEW

**Comment by sirinoks** [comment]
What's up with that failed check? What am I missing @gempir ?

**Comment by gempir** [comment]
I don't have automatic tests setup yet via github CI and the fail was Vercel asking for permissions so it can deploy to a preview env

**Comment by gempir** [comment]
Could you merge main ? I've added some automatic CI

**Comment by gempir** [comment]
Thank you. Very cool!

**Pull request merged**
